title: Samuel Adediran
logo: Data.jpg
description: I am a data driven professional specialising in transforming complex datasets into clear actionable insights that support business and operational decision making. I have experience in data analysis, reporting, and stakeholder-focused insight delivery, with a strong emphasis on data quality and accuracy. I use Advanced Excel for data analysis and automation, and Power BI to create interactive dashboards for effective data storytelling. Additionally, I have working knowledge of SQL and Python for data extraction and analysis, enabling me to deliver insights that are both technically robust and aligned with business needs.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
