title: Samuel Adediran
logo: Data.jpg
description: Data driven professional specialising in transforming complex datasets into actionable insights for business decision making. Skilled in data analysis, reporting, and dashboard development using Advanced Excel and Power BI, with working knowledge of SQL and Python for data extraction and analysis.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
